#ifndef OSCILLATOR_MRO50_IOCTL_H
#define OSCILLATOR_MRO50_IOCTL_H

#define MRO50_MAGIC			'M'
#define CMD_READ_FINE		0x01
#define CMD_READ_COARSE		0x02
#define CMD_ADJUST_FINE		0x03
#define CMD_ADJUST_COARSE	0X04
#define CMD_READ_TEMP		0x05
#define CMD_READ_CTRL		0x06
#define CMD_SAVE_COARSE		0x07

#define MAX_PART_NAME		32

#define MRO50_READ_FINE		_IOR(MRO50_MAGIC, CMD_READ_FINE, u32 *)
#define MRO50_READ_COARSE	_IOR(MRO50_MAGIC, CMD_READ_COARSE, u32 *)
#define MRO50_ADJUST_FINE	_IOW(MRO50_MAGIC, CMD_ADJUST_FINE, u32)
#define MRO50_ADJUST_COARSE	_IOW(MRO50_MAGIC, CMD_ADJUST_COARSE, u32)
#define MRO50_READ_TEMP		_IOR(MRO50_MAGIC, CMD_READ_TEMP, u32 *)
#define MRO50_READ_CTRL		_IOR(MRO50_MAGIC, CMD_READ_CTRL, u32 *)
#define MRO50_SAVE_COARSE	_IO(MRO50_MAGIC, CMD_SAVE_COARSE)


#endif // OSCILLATOR_MRO50_IOCTL_H